[project]
name = "p2p-framework"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiozmq>=1.0.0",
    "attrs>=24.2.0",
]
